### ISSUE TITLE
Inadvertently hardcoded SPI pins

### ISSUE THREAD

**Issue by johnw188** [joshua-8/TMC5072#2]
I pulled your lib as I was starting to work on some drivers, just wanted to give you a heads up:

https://github.com/joshua-8/TMC5072/blob/4d14f52d789657c707a92b8cfc119d734f151b97/src/TMC5072.h#L436-L440

This function takes pin numbers and then ignores them in favor of board defaults. Had me confused for a while.

**Comment by joshua-8** [comment]
Good eye! I appreciate the heads up.

**Comment by joshua-8** [comment]
I have attempted to fix this in version 0.3.6.
I'm sorry this error wasted your time and I appreciate that you shared what you found with me. Best of luck with your project and please let me know if you find any other bugs or suggestions.

**Comment by johnw188** [comment]
Absolutely no worries, thank you for your work I appreciate the jumping off
point. If you’d like I can contribute back a couple things I added, mostly
an “enable stealthchop” that turns on silent mode (which is like seven
values worth of stuff across four registers).

**Comment by joshua-8** [comment]
I would be very grateful for any functions you're willing to contribute. Thank you!
